### Register as Customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Duncan Oyugi",
  "email": "duncanoyugi2001@gmail.com",
  "password": "Dante@1234",
  "phoneNumber": "+254791218163",
  "profileImage": "https://res.cloudinary.com/demo/image/upload/v123456789/avatar.png"
}
