@baseUrl = http://localhost:3000
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDdkYTkyNy0zZGQ3LTQ1ZDMtOGMwMC0wMGM4MGY4ZDFhZGUiLCJlbWFpbCI6ImFkbWluQGNhci1yZW50YWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUxMjgxNjgwLCJleHAiOjE3NTE4ODY0ODB9.wlhBHvEG_46MxmIrVbL7B4HHbEWXiQ8pmpv6bgpEHJ0

### CREATE VEHICLE
POST {{baseUrl}}/vehicle
Authorization: {{authToken}}
Content-Type: application/json

{
  "title": "Toyota Vitz 2020",
  "category": "Economy",
  "pricePerDay": 354,
  "features": ["Automatic", "AC", "Petrol"],
  "imageUrls": [
    "https://www.kar-men.com/adminPanel/uploads/avis/veh_images/1694669747_p9130431.jpg",
    "https://www.kar-men.com/adminPanel/uploads/avis/veh_images/veh_pic_241745476785.JPG"
  ],
  "availableFrom": "2025-07-01T00:00:00.000Z",
  "availableTo": "2025-12-31T00:00:00.000Z",
  "location": "Nairobi"
}

### GET ALL VEHICLES
GET {{baseUrl}}/vehicle
Authorization: {{authToken}}

### UPDATE VEHICLE
PUT {{baseUrl}}/vehicle/beac5f26-4b01-4f7e-a1b3-16c5a50ecea4
Authorization: {{authToken}}
Content-Type: application/json

{
  "title": "Toyota Vitz 2021",
  "category": "Compact",
  "pricePerDay": 375,
  "features": ["Automatic", "AC", "Hybrid"],
  "imageUrls": [
    "https://example.com/image3.jpg"
  ],
  "availableFrom": "2025-08-01T00:00:00.000Z",
  "availableTo": "2025-12-15T00:00:00.000Z",
  "location": "Nakuru"
}

### DELETE VEHICLE
DELETE {{baseUrl}}/vehicle/beac5f26-4b01-4f7e-a1b3-16c5a50ecea4
Authorization: {{authToken}}
